### ISSUE TITLE
more depscription? (suggestion)

### ISSUE THREAD

**Issue by centuryboy774** [refinedmods/rangedpumps#30]
I love this mod but mabye add in the description how to use the pump how it pumps liquid's and do you need to have buckets in it to store the liquid or does it have it's own storage you can put into your bucket. could you transport the liquids via a pipe then it would put them into bucket form which you have to have buckets. just general stuff like this. I have been using mods for some bit so I understand the bare basics but to make the mod more understandable with depth. also put in the dependencies powah mod since you need power unless it adds it's own way to make power then also add this. I love the mod and got it recently and I am still trying to understand it myself. not trying to be mean just trying to make it more understandable for others and if you don't have time I could add description however you do that all you have to do is tell me what to put and stuff. I am just trying to help out and do this if you like it's just a suggestion have  a great day.

**Comment by raoulvdberge** [comment]
Go to the wiki
